version: "2"
services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    image: django_image
    stdin_open: true
    volumes:
      - ./code:/app
    ports:
      - "8080:8080"
