version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./code/:/code
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data: