# Generated by Django 2.2.5 on 2019-10-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcartitem',
            unique_together={('user_key', 'item_key')},
        ),
    ]
