# Generated by Django 2.2.5 on 2019-11-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191021_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='credit_card',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='phone_number',
            field=models.TextField(blank=True),
        ),
    ]
